name: periodic_table
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_linkify: ^4.0.2
  url_launcher: ^5.7.10
  material_design_icons_flutter: ^4.0.5755
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_name: ^0.0.1
flutter_launcher_name:
    name: "Periodic Table"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/logo.webp
      - assets/bg.webp
      - assets/bg2.webp
      - assets/bg1.webp
      - assets/img/1.webp
      - assets/img/2.webp
      - assets/img/3.webp
      - assets/img/4.webp
      - assets/img/5.webp
      - assets/img/6.webp
      - assets/img/7.webp
      - assets/img/8.webp
      - assets/img/9.webp
      - assets/img/10.webp
      - assets/img/11.webp
      - assets/img/12.webp
      - assets/img/13.webp
      - assets/img/14.webp
      - assets/img/15.webp
      - assets/img/16.webp
      - assets/img/17.webp
      - assets/img/18.webp
      - assets/img/19.webp
      - assets/img/20.webp
      - assets/img/21.webp
      - assets/img/22.webp
      - assets/img/23.webp
      - assets/img/24.webp
      - assets/img/25.webp
      - assets/img/26.webp
      - assets/img/27.webp
      - assets/img/28.webp
      - assets/img/29.webp
      - assets/img/30.webp
      - assets/img/31.webp
      - assets/img/32.webp
      - assets/img/33.webp
      - assets/img/34.webp
      - assets/img/35.webp
      - assets/img/36.webp
      - assets/img/37.webp
      - assets/img/38.webp
      - assets/img/39.webp
      - assets/img/40.webp
      - assets/img/41.webp
      - assets/img/42.webp
      - assets/img/43.webp
      - assets/img/44.webp
      - assets/img/45.webp
      - assets/img/46.webp
      - assets/img/47.webp
      - assets/img/48.webp
      - assets/img/49.webp
      - assets/img/50.webp
      - assets/img/51.webp
      - assets/img/52.webp
      - assets/img/53.webp
      - assets/img/54.webp
      - assets/img/55.webp
      - assets/img/56.webp
      - assets/img/57.webp
      - assets/img/58.webp
      - assets/img/59.webp
      - assets/img/60.webp
      - assets/img/61.webp
      - assets/img/62.webp
      - assets/img/63.webp
      - assets/img/64.webp
      - assets/img/65.webp
      - assets/img/66.webp
      - assets/img/67.webp
      - assets/img/68.webp
      - assets/img/69.webp
      - assets/img/70.webp
      - assets/img/71.webp
      - assets/img/72.webp
      - assets/img/73.webp
      - assets/img/74.webp
      - assets/img/75.webp
      - assets/img/76.webp
      - assets/img/77.webp
      - assets/img/78.webp
      - assets/img/79.webp
      - assets/img/80.webp
      - assets/img/81.webp
      - assets/img/82.webp
      - assets/img/83.webp
      - assets/img/84.webp
      - assets/img/85.webp
      - assets/img/86.webp
      - assets/img/87.webp
      - assets/img/88.webp
      - assets/img/89.webp
      - assets/img/90.webp
      - assets/img/91.webp
      - assets/img/92.webp
      - assets/img/93.webp
      - assets/img/94.webp
      - assets/img/95.webp
      - assets/img/96.webp
      - assets/img/97.webp
      - assets/img/98.webp
      - assets/img/99.webp
      - assets/img/100.webp
      - assets/img/101.webp
      - assets/img/102.webp
      - assets/img/103.webp
      - assets/img/104.webp
      - assets/img/105.webp
      - assets/img/106.webp
      - assets/img/107.webp
      - assets/img/108.webp
      - assets/img/109.webp
      - assets/img/110.webp
      - assets/img/111.webp
      - assets/img/112.webp
      - assets/img/113.webp
      - assets/img/114.webp
      - assets/img/115.webp
      - assets/img/116.webp
      - assets/img/117.webp
      - assets/img/118.webp
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
